In [ ]:
import numpy as np

__3.1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

a) m = 4, n1 = 2, n2 = 4, k = 2 <br>
$ n1 \neq n2 $ <br>
$ A\cdot B \neq , B\cdot A \neq$

б) m = 2, n1 = 5, n2 = 5, k = 3 <br>
$ n1 == n2, m \neq k $ <br>
$ A\cdot B = 2X3 , B\cdot A \neq$

в) m = 8, n1 = 3, n2 = 3, k = 8 <br>
$ n1 == n2, m == k $ <br>
$ A\cdot B = 8X8 , B\cdot A = 3X3$

г) m = 4, n1 = 4, n2 = 4, k = 4 <br>
$ n1 == n2,  m == k $ <br>
$ A\cdot B = 4X4 , B\cdot A = 4X4$

__3.2.__ Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$ A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} =
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix} $$

$ A \cdot B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} =
\begin{pmatrix}
(1\cdot 4 + (-2) \cdot 0) & (1 \cdot (-1) + (-2) \cdot 5)\\ 
(3 \cdot 4 + 0 \cdot 0) & (3 \cdot (-1) + 0 \cdot 5)
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$ B \cdot A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} =
\begin{pmatrix}
(4\cdot 1 + (-1) \cdot 3) & (4 \cdot (-2) + (-1) \cdot 0)\\ 
(0 \cdot 1 + 5 \cdot 3) & (0 \cdot (-2) + 5 \cdot 0)
\end{pmatrix} = 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$



In [ ]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0,5]])  
print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


$3A-2B+4C=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix} $

In [ ]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2,-1]]) 
C = np.array([[2, -4], [1,1]]) 

print(f'Матрица 3A-2B + 4C\n{3*A - 2*B + 4*C}')


Матрица 3A-2B + 4C
[[ 11  -5]
 [  9 -12]]


__3.4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$
$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
(4 \cdot 4 + 1\cdot 1) & (4 \cdot 5 + 1 \cdot (-2)) & (4 \cdot 2 + 1 \cdot 3)\\ 
(5 \cdot 4 + (-2) \cdot 1) & (5 \cdot 5 + (-2) \cdot (-2)) & (5 \cdot 2 + (-2) \cdot 3) \\
(2 \cdot 4 + 3 \cdot 1) & (2 \cdot 5 + 3 \cdot (-2)) & (2 \cdot 2 + 3 \cdot 3)
\end{pmatrix}=
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$ 

$A^{T}A = \begin{pmatrix}
(4^2 + 5^2 + 2^2) & (4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3) \\
(1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2) & (1^2 + (-2)^2 + 3^2) 
\end{pmatrix}=
\begin{pmatrix}
45 & 0 \\ 
0 & 14 
\end{pmatrix}$

In [ ]:
A = np.array([[4, 1], [5, -2], [2,3]])

print(f'Транспонированная матрица A_T: \n{A.T}')
print(f'Произведеие A*A_T: \n{A.dot(A.T)}')
print(f'Произведение A_T*A: \n{A.T.dot(A)}')

Транспонированная матрица A_T: 
[[ 4  5  2]
 [ 1 -2  3]]
Произведеие A*A_T: 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение A_T*A: 
[[45  0]
 [ 0 14]]



__3.5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def mult_func(A, B):
    return [[sum(a * b for a, b in zip(row_a, col_b)) for col_b in zip(*B)] for row_a in A]

In [ ]:
A = np.array([[1, 1], [2, 2]])
B = np.array([[0, 3], [-2,0]]) 

In [ ]:
mult_func(A, B)

[[-2, 3], [-4, 6]]

In [ ]:
A.dot(B)

array([[-2,  3],
       [-4,  6]])

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__4.1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^2x + cos^2x = 1$$

   б)
    Нижняя треугольная матрица
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4*5*9 = 180$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1\cdot5\cdot9 + 2 \cdot 6 \cdot 7 + 3 \cdot 4 \cdot 8 - 7\cdot 5 \cdot 3 - 8\cdot 6 \cdot 1 - 9 \cdot 4 \cdot 2 = 45 + 84 + 96 - 105 - 48 - 72 = 0$$


In [ ]:
B = np.array([[4,2,3], [0,5,1], [0,0,9]])
C = np.array([[1,2,3], [4,5,6,], [7,8,9]])
np.linalg.det(B)

180.0

In [ ]:
np.linalg.det(C)

0.0

__4.2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2^ndet(A) = 2^n \cdot 4$, где n - количество строк

__4.3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2\cdot(-14)\cdot13 + 7 \cdot 6 \cdot (-3) + (-3) \cdot 4 \cdot 7 - (-3)\cdot (-14)\cdot (-3) - 7\cdot 6 \cdot (-2) - 13 \cdot 4 \cdot 7 = 364 - 126 - 84 + 126 + 84 - 364 = 0 $$

$detA = 0$, для нее не существует обратной матрицы. A - вырожденная матрица.

In [ ]:
A = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
np.linalg.det(A)

0.0


__4.4__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$
Третья строка сумма первых двух, убираем её.
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$
Вычитаем вторую строку из первой

 $\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix}$

rank = 2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ третья строка сумма првой и второй, значит можно убрать.

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ 

rank = 3

In [ ]:
a = np.array([[1,2,3], [1,1,1], [2,3,4]])
b = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
rank_a, rank_b

(2, 3)