In [ ]:
import numpy as np

__5.1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Собственное значение:
$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)(6-\lambda)-(-6)\cdot2=0$$
$$(\lambda+1)(\lambda-6)+12=0$$
$$\lambda^2 - 6\lambda + \lambda - 6 +12=0$$
$$\lambda^2 - 5\lambda +6 = 0$$
$$\lambda_{1} = 2 \ \lambda_{2} = 3$$


Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

При $\lambda = 2$
получим
$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-3x_{1}-6x_{2}= 0, \\
2x_{1} + 4x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
3x_{1}= -6x_{2}, \\
x_{1} = -2x_{2}
\end{cases}$$ 
Может быть вектор $\begin{pmatrix}
0\\ 
0
\end{pmatrix}$ $\begin{pmatrix}
-2\\ 
1
\end{pmatrix}$


При $\lambda = 3$
получим
$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2x_{1}+6x_{2}= 3x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-4x_{1}-6x_{2}= 0, \\
2x_{1} + 3x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
2x_{1}= -3x_{2}, \\
x_{1} = -1,5x_{2}
\end{cases}$$ 
Может быть вектор $\begin{pmatrix}
0\\ 
0
\end{pmatrix}$ $\begin{pmatrix}
-3\\ 
2
\end{pmatrix}$


In [ ]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__5.2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Собственное значение:
$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)^2=0$$
$$\lambda = -1$$


Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1 \cdot
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}= -x_{1} \\
-x_{2} = -x_{2}
\end{cases}$$ 

$$\begin{cases}
x_{1}= x_{1}, \\
x_{2} = x_{2}
\end{cases}$$ 
Могут быть любые $x_{1}, x_{2}$.

In [ ]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__5.3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}
$$

$$\begin{cases}
1+1= \lambda \\
-1+3= \lambda
\end{cases}$$ 

$$\begin{cases}
\lambda = 2 \\
\lambda = 2
\end{cases}$$ 
Да, заданный вектор $\begin{pmatrix}
1\\ 
1
\end{pmatrix}$ является собственным.

In [ ]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}') 
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}
$$

$$\begin{cases}
0 - 9 + 0 = 3\lambda \\
9 + 0 + 0 = -3\lambda \\
0 + 0 - 12 = -4\lambda
\end{cases}$$ 

$$\begin{cases}
\lambda = -3 \\
\lambda = -3 \\
\lambda = 3
\end{cases}$$ 
Все $\lambda$ не равны между собой, система не имеет смысла, значит, заданный вектор $\begin{pmatrix}
3\\ 
-3 \\
-4
\end{pmatrix}$ не является собственным.

In [ ]:
a = np.array([[0, 3, 0], [3, 0, 0], [0,0,3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}') 
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
